[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
hook_add = '''
   if dein#util#_is_windows()
       let cmd = 'tools\\update-all-mingw'
   elseif dein#util#_is_cygwin()
       let cmd = 'make -f make_cygwin.mak'
   elseif executable('gmake')
       let cmd = 'gmake'
   else
       let cmd = 'make'
   endif
   let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    au MyAutoCmd VimEnter * nested colorscheme jellybeans
'''

# --------------------------
# Quickrun
# --------------------------
[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
call LoadMySource('plugins/quickrun.rc.vim')
'''

# --------------------------
# Expand Region
# --------------------------
[[plugins]]
repo = "terryma/vim-expand-region"

